version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: prompt_library
      MYSQL_USER: promptuser
      MYSQL_PASSWORD: promptpass123
      MYSQL_ROOT_PASSWORD: rootpass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key
      - DATABASE_URL=mysql://promptuser:promptpass123@db:3306/prompt_library
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
      - redis

  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"

volumes:
  mysql_data:
