# Generated by Django 5.2.5 on 2025-08-26 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(choices=[('general', 'Câu hỏi chung'), ('prompt-request', 'Đề xuất prompt mới'), ('bug-report', 'Báo lỗi'), ('partnership', 'Hợp tác'), ('feedback', 'Phản hồi'), ('support', 'Hỗ trợ kỹ thuật')], max_length=20, verbose_name='Chủ đề')),
                ('message', models.TextField(verbose_name='Tin nhắn')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('in_progress', 'Đang xử lý'), ('resolved', 'Đã xử lý'), ('closed', 'Đã đóng')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('admin_reply', models.TextField(blank=True, help_text='Phản hồi từ quản trị viên', verbose_name='Phản hồi từ admin')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày phản hồi')),
                ('user', models.ForeignKey(blank=True, help_text='Người dùng đã đăng nhập (nếu có)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Tin nhắn liên hệ',
                'verbose_name_plural': 'Tin nhắn liên hệ',
                'ordering': ['-created_at'],
            },
        ),
    ]
